[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pjdev-va-ois-emass-api-client"
dynamic = ["version"]
description = ''
readme = "README.md"
requires-python = ">=3.12"
license = "MIT"
keywords = []
authors = [
  { name = "Purple Jay LLC", email = "devs@purplejay.io" },
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = [
  "httpx>=0.28.1",
  "pydantic>=2.10.6",
  "pydantic-settings>=2.8.1",
  "tenacity>=9.0.0",
  "loguru",
]

[project.optional-dependencies]
dev = [
    "ruff",
]

test = [
    "pytest",
    "coverage"
]

[project.urls]
Documentation = "https://gitlab.purplejay.net/va-ois/ad-hoc-request/emass-api-client#readme"
Issues = "https://gitlab.purplejay.net/va-ois/ad-hoc-request/emass-api-client/issues"
Source = "https://gitlab.purplejay.net/va-ois/ad-hoc-request/emass-api-client"

[tool.hatch.version]
path = "src/pjdev_va_ois_emass_api_client/__about__.py"

[tool.hatch.envs.types]
extra-dependencies = [
  "mypy>=1.0.0",
]
[tool.hatch.envs.types.scripts]
check = "mypy --install-types --non-interactive {args:src/pjdev_va_ois_emass_api_client tests}"

[tool.coverage.run]
source_pkgs = ["pjdev_va_ois_emass_api_client", "tests"]
branch = true
parallel = true
omit = [
  "src/pjdev_va_ois_emass_api_client/__about__.py",
]

[tool.coverage.paths]
pjdev_va_ois_emass_api_client = ["src/pjdev_va_ois_emass_api_client", "*/pjdev-va-ois-emass-api-client/src/pjdev_va_ois_emass_api_client"]
tests = ["tests", "*/pjdev_va_ois_emass_api_client/tests"]

[tool.coverage.report]
exclude_lines = [
  "no cov",
  "if __name__ == .__main__.:",
  "if TYPE_CHECKING:",
]
