[tool.poetry]
name = "agentbuddy"
version = "0.2.0a3"
description = ""
authors = ["2mmanu <emmanuele.lacavalla@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9,<3.13"
langchain = "^0.3.20"
langgraph = "^0.3.7"
langchain-ollama = "^0.2.3"


[tool.poetry.group.dev.dependencies]
pytest = "^8.3.5"
fastapi = "^0.115.11"
uvicorn = "^0.34.0"
python-keycloak = "^5.3.1"
jinja2 = "^3.1.6"
pymongo = "^4.11.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
