[project]
name = "fbrcode-logger"
version = "0.4.0"
description = ""
authors = [
    {name = "fbrcode",email = "fabio.bressler@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
]

[tool.poetry]
packages = [{include = "fbrcode_logger", from = "src"}]


[tool.poetry.group.dev.dependencies]
pytest = "^8.3.5"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
