[project]
name = "morphcloud"
version = "0.1.29"
description = "A Python SDK and CLI tool for creating, managing, and interacting with Morph Cloud VMs."
authors = [
    {name = "Morph Labs", email = "jobs@morph.so"}
]
license = {text = "Apache-2.0"}
readme = "README.md"
requires-python = ">=3.11"
keywords = ["morph", "cloud", "runtimes", "cli"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
]
dependencies = [
    "requests>=2.32.3",
    "tqdm>=4.67.1",
    "httpx>=0.28.1",
    "pydantic>=2.10.3",
    "psutil>=6.1.0",
    "anthropic>=0.40.0",
    "click>=8.1.7",
    "paramiko>=3.5.0",
    "pathspec>=0.12.1",
]

[project.scripts]
morphcloud = "morphcloud.cli:cli"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
