[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mcp-perforce"
version = "0.1.4"
description = "mcp server of Perforce Swarm"
readme = "README.md"
requires-python = ">=3.12"
license = {text = "MIT"}
authors = [
    {name = "tiaoyu", email = "your.email@example.com"}
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "httpx>=0.28.1",
    "map[cli]>=1.3.0",
    "requests",
    "bs4",
    "mcp",
]

[project.urls]
"Homepage" = "https://github.com/yourusername/mcp-perforce"
"Bug Tracker" = "https://github.com/yourusername/mcp-perforce/issues"

[project.scripts]
mcp-perforce = "mcp_perforce.main:main"

[tool.setuptools]
packages = ["mcp_perforce"]