[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "vto-geodat"
version = "0.0.2"
description = "Just a personal test app, not intended for use by anyone else"
readme = "README.md"
requires-python = ">= 3.13"
# dependencies = []
license = "MIT"
license-files = ["LICEN[CS]E*"]

[project.urls]
# Repository = ""