[project]
name = "zmp-openapi-mcp-server"
version = "0.1.1"
description = ""
authors = [
    {name = "Kilsoo Kang",email = "kilsoo75@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.11,<4.0"
dependencies = [
    "zmp-openapi-toolkit (>=0.1.2,<0.2.0)",
    "click (>=8.1.8,<9.0.0)",
    "mcp (>=1.4.0,<2.0.0)"
]

[project.scripts]
zmp-openapi-mcp-server = "zmp_openapi_mcp_server:main"

[tool.poetry]
package-mode = true
packages = [
    { include = "zmp_openapi_mcp_server", from = "src" },
]

include = [
    { path = "src/zmp_openapi_mcp_server/openapi/**/*", format = ["sdist", "wheel"] }
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
