[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "onad"
version = "0.0.10"
description = "Online Anomaly Detection Models"
authors = [
  { name = "Oliver Hennhoefer", email = "oliver.hennhoefer@mail.de" },
]
license = { file = "LICENSE" }
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3.10",
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent",
]
requires-python = ">=3.10"
dependencies = [
    "numpy>=2.2.3",
    "faiss-cpu>=1.10.0",
    "tqdm>=4.67.1",
    "scipy>=1.15.2"
]

[project.optional-dependencies]
dev = ["black", "river>=0.22.0"]
eval = ["scikit-learn>=1.6.1"]
dl = ["torch>=2.6.0"]
all = ["black", "river>=0.22.0", "scikit-learn>=1.6.1", "torch>=2.6.0"]

[project.urls]
"Homepage" = "https://github.com/OliverHennhoefer/onad"
"Bugs" = "https://github.com/OliverHennhoefer/onad/issues"