[project]
name = "browser-mcp"
version = "0.1.2"
description = "MCP server for browser-use"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mcp[cli]>=1.3.0",
    "browser-use>=0.1.4",
    "ruff>=0.9.10",
    "langchain-openai>=0.3.1",
    "python-dotenv>=1.0.1",
    "playwright>=1.50.0",
    "uv>=0.1.0",
    "pytest>=7.4.0",
]

[project.scripts]
browser-mcp = "browser_mcp.server:run"
browser-mcp-run = "__main__:main"

[project.urls]
"Homepage" = "https://github.com/pranav7/browser-mcp"
"Bug Tracker" = "https://github.com/pranav7/browser-mcp/issues"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["browser_mcp"]
