[project]
name = "nonary"
version = "0.1.2"
description = "CLI tool for The Nonary games"
readme = "README.md"
authors = [
    { name = "Jorge GÃ³mez Zarzosa", email = "jorge.gomez@gmail.com" }
]
requires-python = ">=3.9"
dependencies = []

[project.urls]
Source = 'https://github.com/jorgegomzar/nonary'

[project.scripts]
nonary = "nonary:cli_entrypoint"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
