# Copyright (c) 2023-2024 Datalayer, Inc.
#
# Datalayer License

[build-system]
requires = ["hatchling==1.21.1", "jupyterlab==4.0.9", "hatch-nodejs-version"]
build-backend = "hatchling.build"

[project]
name = "jupyter_kernels"
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.9"
classifiers = [
    "Framework :: Jupyter",
    "Framework :: Jupyter :: JupyterLab",
    "Framework :: Jupyter :: JupyterLab :: 4",
    "Framework :: Jupyter :: JupyterLab :: Extensions",
    "Framework :: Jupyter :: JupyterLab :: Extensions :: Prebuilt",
    "Intended Audience :: Developers",
    "Intended Audience :: System Administrators",
    "Intended Audience :: Science/Research",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
dependencies = [
    "datalayer_core>=1.0.0",
    "jupyter_server>=2.10,<3",
    "jupyter_client>=8.6.0",
    "jupyter_console",
    "jupyter_iam",
    "keyring",
    "prompt_toolkit>=3.0.0",
    "questionary>=2",
    "requests",
    "rich",
    "websocket-client"
]
dynamic = ["version", "description", "authors", "urls", "keywords"]

[project.optional-dependencies]
test = [
    "coverage",
    "pytest",
    "pytest-asyncio",
    "pytest-cov",
    "pytest-jupyter",
    "pytest-tornasync",
]

[project.scripts]
jk = "jupyter_kernels.application:main"
jupyter-kernels = "jupyter_kernels.application:main"
jupyter-kernels-server = "jupyter_kernels.serverapplication:main"

[tool.hatch.version]
source = "nodejs"

[tool.hatch.build]
artifacts = [
    "jupyter_kernels/static",
    "jupyter_kernels/templates",
]

[tool.hatch.build.hooks.custom]

[tool.hatch.metadata.hooks.nodejs]
fields = ["description", "authors", "urls"]

[tool.hatch.build.targets.sdist]
artifacts = [
    "jupyter_kernels/static",
    "jupyter_kernels/labextension"
]
exclude = [".github", "binder", ".yarn"]

[tool.hatch.build.targets.wheel]
artifacts = [
    "jupyter_kernels/static",
]

[tool.hatch.build.targets.wheel.shared-data]
"jupyter_kernels/labextension" = "share/jupyter/labextensions/@datalayer/jupyter-kernels"
"install.json" = "share/jupyter/labextensions/@datalayer/jupyter-kernels/install.json"
"jupyter-config/server-config" = "etc/jupyter/jupyter_server_config.d"
"jupyter-config/nb-config" = "etc/jupyter/jupyter_notebook_config.d"

[tool.hatch.build.hooks.version]
path = "jupyter_kernels/_version.py"

[tool.hatch.build.hooks.jupyter-builder]
dependencies = ["hatch-jupyter-builder>=0.5"]
build-function = "hatch_jupyter_builder.npm_builder"
ensured-targets = [
    "jupyter_kernels/labextension/static/style.js",
    "jupyter_kernels/labextension/package.json",
]
skip-if-exists = ["jupyter_kernels/labextension/static/style.js"]

[tool.hatch.build.hooks.jupyter-builder.build-kwargs]
build_cmd = "build:prod"
npm = ["jlpm"]

[tool.hatch.build.hooks.jupyter-builder.editable-build-kwargs]
build_cmd = "install:extension"
npm = ["jlpm"]
source_dir = "src"
build_dir = "jupyter_kernels/labextension"

[tool.jupyter-releaser.options]
version_cmd = "hatch version"
