[project]
name = "imuthes-crypt"
version = "0.0.0a3"
description = "Crypt Tools"
license = { text = "LGPL-3.0-or-later" }
readme = "README.md"
requires-python = ">=3.13,<4.0"
authors = [
    { name = "Bernhard Radermacher", email = "bernhard.radermacher@netlink-consulting.com" }
]
classifiers = [
    "Topic :: Software Development",
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: GNU Lesser General Public License v3 or later (LGPLv3+)",
    "Topic :: Utilities"
]
dependencies = [
    "imuthes (>=0.0.0a3,<1.4.0)",
    "cryptography (>=44.0.2,<45.0.0)",
    "click-default-group (>=1.2.4,<2.0.0)"
]

[project.urls]
repository = "https://gitlab.com/imuthes/crypt"

[project.scripts]
imuthes-crypt = "imuthes.crypt.cli:main"

[tool.poetry]
packages = [
    { include = "imuthes/crypt" }
]

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
black = "^25.1.0"
ruff = "^0.9.10"

[tool.poetry.group.test]
optional = true

[tool.poetry.group.test.dependencies]
pytest = "^8.3.5"
pytest-cov = "^6.0.0"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120
target-version = ['py313']
include = '\.pyi?$'

[tool.ruff]
line-length = 120
target-version = 'py313'

[tool.pytest.ini_options]
filterwarnings = [
    'ignore:Deprecated call to `pkg_resources.declare_namespace:DeprecationWarning',
    'ignore:pkg_resources is deprecated as an API:DeprecationWarning',
]
addopts = "--cov=imuthes --cov-report html:__coverage"


