[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "SimpleMDDataCatalog"
version = "0.0.11"
authors = [
  { name="Joep van Genuchten", email="joep@uuidea.eu" },
]
description = "A simple package that supports data catalogging in a spreadsheet and publishes the data catalog as markdown on git(hub)"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
]

dependencies = [
    "pandas",
    "rdflib",
    "igraph",
    "matplotlib","wordcloud","validators", "openpyxl"
]


[project.urls]
Homepage = "https://github.com/uuidea/SimpleMDDataCatalog"
Issues = "https://github.com/uuidea/SimpleMDDataCatalog/issues"
