[build-system]
requires = ["setuptools>=69.0.2","wheel==0.42.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = [ "seavad" ]

[project]
name = "seavad"
version = "0.0.5"
description = "SeaVAD: Voice Activity Detection module with silero and state machine."
license = { file = "LINCENSE"}
readme = "readme_for_pypi.md"
requires-python = ">=3.8"
authors = [
    { name = "Seasalt.ai", email = "info@seasalt.ai" },
]
dependencies = [
    "pydantic>=1.9",
    "onnxruntime>=1.16.3",
    "onnxruntime_extensions>=0.11.0",
    "importlib-resources>=6.4.5",
    "pytest>=8.3.4",
    "pyloudnorm>=0.1.1",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]


[project.optional-dependencies]
dev = [
    "black==23.3.0",
    "isort==5.12.0",
    "pyright==1.1.314"
]
test = [
    "pytest"
]
build = [
    "twine==4.0.2",
    "build==1.0.3"
]

[tool.pyright]
reportImplicitStringConcatenation = "none"
reportPrivateImportUsage = "none"

pythonVersion = "3.8"
pythonPlatform = "Linux"

[tool.isort]
profile = "black"
line_length = 127
known_first_party = "seavad"

[tool.black]
line-length = 127