[tool.poetry]
name = "home_assistant_eltako_frontend"
version = "0.0.8"
description = "A Python package that includes static files"
readme = "README.md"
# requires-python = ">=3.7"
license = "MIT"
keywords = ["enocean", "eltako", "home assistant", "frontend", "static files"]
authors = ["Philipp Grimm"]
packages = [ 
    {include ="static", to = "home_assistant_eltako_frontend"}, 
    {include="__init__.py", to = "home_assistant_eltako_frontend"} ]
include = [ 
    "static/**/*.html", 
    "static/**/*.js", 
    "static/**/*.css", 
    "__init__.py" ]

[tool.poetry.dependencies]
build = "*"
wheel = "*"

[tool.poetry.scripts]
post_install = "post_install:compile_typescript"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.build]
generate-setup-file = true
