[build-system]
requires = [
    "setuptools>=42",
    "wheel",
]
build-backend="setuptools.build_meta"

[project]
name = "zibanu-django-repository"
dynamic = ["version"]
authors = [
    {name="Mario CerÃ³n", email="mario.ceron@cqinversiones.co"}
]
description = "Zibanu repository library for django projects"
readme = "README.md"
license = {file="LICENSE"}
requires-python = ">=3.9"
classifiers = [
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Programming Language :: Python :: 3.9",
    "Development Status :: 5 - Production/Stable",
    "Framework :: Django",
    "Framework :: Django :: 3.2",
    "Environment :: Web Environment",
    "Operating System :: OS Independent",
    "Topic :: Internet :: WWW/HTTP"
]
dependencies = [
    "Django>=3.2",
    "zibanu-django>=2.0.0",
]
keywords = [
    "django",
    "zibanu",
    "library",
    "auth"
]

[tool.setuptools.dynamic]
version = {attr= "zibanu.django.repository.__version__"}