[project]
name = "eg4_inverter_api"
version = "0.1.5"
description = "A Python API for interacting with EG4 Inverter systems."
authors = [
    { name = "Garreth Jeremiah", email = "twistedroutes76@example.com" }
]
readme = "README.md"
requires-python = ">=3.8"
license = { text = "Apache-2.0" }
keywords = ["EG4", "Inverter", "API", "Energy", "Battery"]
dependencies = [
    "aiohttp>=3.8.1",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0",
    "pytest-asyncio>=0.20",
    "python-dotenv>=1.0.0"
]

[tool.setuptools.packages.find]
where = ["src"]

[project.urls]
Homepage = "https://github.com/twistedroutes/eg4_inverter_api"
Repository = "https://github.com/twistedroutes/eg4_inverter_api"
Issues = "https://github.com/twistedroutes/eg4_inverter_api/issues"