[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[project]
name = "dnms_task"
description = "Delayed Non-Match-To-Sample task for IBLRIG"
version = "0.1.2"
authors = [{ name="Tatiana Dupak", email="tatiana.dupak@u-bordeaux.fr" }]
keywords = [ "IBL", "neuro-science"]
requires-python = ">=3.10"
readme = "README.md"
license = { file = "LICENSE" }

[project.entry-points."iblrig.plugins"]
task_dnms = "task:Session"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"*"= ["src/*.py", "src/*.yaml", "src/*.yml"]