[build-system]
requires = ["hatchling==1.27.0"]
build-backend = "hatchling.build"

[project]
name = "clypi"
description = "Your all-in-one for beautiful, lightweight, prod-ready CLIs"
readme = "README.md"
version = "1.0.12"
license = "MIT"
license-files = ["LICEN[CS]E*"]
requires-python = ">=3.11"
authors = [
  {name = "Daniel Melchor", email = "dmelchor@pm.me"},
]
keywords = ["cli", "terminal", "ui"]
dependencies = [
    "python-dateutil>=2.9.0.post0",
    "typing-extensions>=4.4.0",
]


[project.urls]
Documentation = "https://github.com/danimelchor/clypi/blob/master/docs/index.md"
Homepage = "https://github.com/danimelchor/clypi"
Repository = "https://github.com/danimelchor/clypi"
Issues = "https://github.com/danimelchor/clypi/issues"

[project.optional-dependencies]
dev = [
  "ruff>=0.9.7",
  "pyright>=1.1.396",
  "mypy>=1.15.0",
  "pytest>=8.3.5",
  "codespell>=2.4.1",
  "anyio>=4.8.0",
  "types-python-dateutil>=2.9.0.20241206",
]

[tool.pytest.ini_options]
minversion = "8.0"
addopts = "-ra -q"
testpaths = ["tests"]

[tool.pyright]
exclude = [
    "**/__pycache__",
]
# strict = ["clypi/"]
reportMissingTypeStubs = false

[tool.bandit]
skips = ["B101"]
