[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "nidec-inventory"
dynamic = ["version"]
dependencies = [
    "pandas~=2.2.3",
    "PyYAML~=6.0.2",
    "setuptools~=75.8.2",
#    "openpyxl~=3.2.0b1",
]
authors = [
    { name = "Carlos Alonso Martín", email = "cam.codeweaver@gmail.com" },
]
maintainers = [
    { name = "Carlos Alonso Martín", email = "cam.codeweaver@gmail.com" },
]
description = "Nidec Unidrive M motor control drives inventory generator."
readme = { file = "README.md", content-type = "text/markdown" }
license = { file = "LICENSE", content-type = "text/markdown" }

keywords = [
	"nidec",
    "variador",
    "accionamiento",
    "ac drives",
    "servo drives",
    "high performance ac drives",
    "m700",
    "m300",
    "m200",
]

classifiers = [
    "License :: OSI Approved :: MIT License",
    "Development Status :: 2 - Pre-Alpha",
    "Environment :: Console",
    "Programming Language :: Python",
    "Topic :: Documentation",
    "Topic :: Office/Business",
    "Topic :: Utilities",
]