name: ğŸ“¦ Publish Python Package

on:
  release:
    types: [published]
  # push:
  #   branches:
  #     - Python

permissions:
  contents: read

jobs:
  build:
    name: ğŸ“¦ Build distribution
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: ğŸ› ï¸ Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"
    - name: ğŸ› ï¸ Install flit
      run: python3 -m pip install flit --user
    - name: ğŸ› ï¸ Build a binary wheel and a source tarball
      run: python3 -m flit build
    - name: ğŸ’¾ Store the distribution packages
      uses: actions/upload-artifact@v4
      with:
        name: python-package-distributions
        path: dist/

  pypi-publish:
    name: â¬†ï¸ Upload release to PyPI
    needs:
      - build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/behaverse-data-loader
    permissions:
      id-token: write  # for trusted publishing
    steps:
    - name: â¬‡ï¸ Download the distribution packages
      uses: actions/download-artifact@v4
      with:
        name: python-package-distributions
        path: dist/
    - name: ğŸš€ Publish distribution to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
