[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "vllmocr"
version = "0.3.8"
description = "OCR project using LLMs"
readme = "README.md"
keywords = ["ocr", "llm", "image processing", "vllm"]
classifiers = [
 "Development Status :: 3 - Alpha",
 "Intended Audience :: Developers",
 "License :: OSI Approved :: MIT License", # Assuming MIT License
 "Programming Language :: Python :: 3",
 "Programming Language :: Python :: 3.9",
 "Programming Language :: Python :: 3.10",
 "Programming Language :: Python :: 3.11",
 "Programming Language :: Python :: 3.12",
]
dependencies = [
"opencv-python",
"anthropic",
 "pytest",
 "pytest-mock",
 "openai",
 "google-genai",
 "ollama",
 "requests",
 "PyMuPDF",
 "opencv-python-headless",
 "python-dotenv",
 "typing-extensions",
]

[project.scripts]
vllmocr = "vllmocr.main:main"

[project.optional-dependencies]
dev = [
 "pytest>=8.3.5",
]