[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "simple-rabbit-broker"
version = "0.0.2"
authors = [
  { name="Nikita Sysoev", email="nylinary@gmail.com" },
]
description = "RPC имплементация брокера RabbitMQ"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "aio-pika~=9.0.2",
    "django-environ~=0.9.0",
    "pydantic~=2.10.6",
]

[tool.hatch.build.targets.wheel]
packages = ["rabbit_broker/"]
