[project]
name = "pubmedtool"
version = "0.1.0"
description = ""
authors = [
    {name = "Pushpender",email = "pushpenderjangra2005@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "requests (>=2.32.3,<3.0.0)"
]

[tool.poetry]
packages = [{include = "pubmedtool", from = "src"}]

[tool.poetry.scripts]
get-papers-list = "cli:main"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
