[build-system]
requires = ["setuptools == 69.4.0", "wheel == 0.43.0", "setuptools-scm == 8.0.4"]
build-backend = "setuptools.build_meta"

[project]
name = "tomillo"
description="Configuration system."
readme = "README.md"
authors = [{name = "bashiron", email = "bioshiron@gmail.com"}]
requires-python = ">= 3.12"
keywords = []
dynamic = ["version"]
dependencies = [
    'loguru == 0.7.3',
    'tomlkit==0.13.2'
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3.12",
    "Topic :: Software Development :: Libraries",
    'Intended Audience :: Developers',
]

[project.urls]
Homepage = "https://github.com/bashiron/tomillo"
Issues = "https://github.com/bashiron/tomillo/issues"

[tool.setuptools_scm]
version_file = "src/tomillo/_version.py"
