[project]
name = "hakisto"
version = "0.3.4a1"
description = "Logging reimagined"
license = "LGPL-3.0-or-later"
authors = [
    { name = "Bernhard Radermacher", email = "bernhard.radermacher@netlink-consulting.com" }
]
readme = "README.md"
repository = "https://gitlab.com/hakisto/logger"
documentation = "https://hakisto.readthedocs.io/"
keywords = ["logging"]
classifiers = [
    "Topic :: Software Development",
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: GNU Lesser General Public License v3 or later (LGPLv3+)",
    "Topic :: Utilities"
]
packages = [{ include = "hakisto" }]

requires-python = ">=3.13,<4.0"

dependencies = [
    "pypubsub (>=4.0.3,<5.0.0)"
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
hakisto-demo-color = "hakisto.demo:color"
hakisto-demo-critical = "hakisto.demo:critical"
hakisto-demo-traceback = "hakisto.demo:traceback"

[tool.poetry.group.docs]
optional = true

[tool.poetry.group.docs.dependencies]
sphinx = "^8.2.3"
sphinx-rtd-theme = "^3.0.2"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
black = "^25.1.0"
pytest = "^8.3.5"
pytest-cov = "^6.0.0"
ruff = "^0.9.10"

[tool.black]
line-length = 120
target-version = ['py313']
include = '\.pyi?$'

[tool.ruff]
line-length = 120
target-version = 'py313'


[tool.pytest.ini_options]
filterwarnings = ['ignore:pkg_resources is deprecated as an API:DeprecationWarning', ]
addopts = "--cov=hakisto --cov-report html:__coverage"
