[workspace]
members = ["crates/python"]
resolver = "2"

[workspace.package]
edition = "2021"

[workspace.dependencies]
polars = { version = "0.46.0", default-features = false }
polars-arrow = "0.46.0"
