[build-system]
requires = [
  "setuptools >= 61.0",
  "toml"
]
build-backend = "setuptools.build_meta"

[project]
dynamic = ["readme"]
name = "pylegs"
version = "0.4.11"
requires-python = ">= 3.9"
description = "Legacy Survey Data Retriever"
keywords = ["astronomy", "surveys", "catalogs", "images"]
authors = [
  {name = "Natanael Magalhães Cardoso", email = "contact@natanael.net"}
]
maintainers = [
  {name = "Natanael Magalhães Cardoso", email = "contact@natanael.net"}
]
dependencies = [
  "wheel",
  "numpy>=1.21.6",
  "pandas>=1.3.5",
  "tqdm>=4.64.1",
  "requests>=2.23",
  "Pillow>=7.1.2",
  "astropy>=5.2",
  "matplotlib",
  "pypdf",
  "pyarrow",
  "spherical_geometry",
  "beautifulsoup4",
  "scipy",
  "astro-datalab",
]

[project.optional-dependencies]
docs = [
  "Jinja2>=3.1",
  "sphinx",
  "sphinx_copybutton",
  "sphinx-astropy",
  "sphinx-gallery",
  "sphinx-automodapi",
  "numpydoc",
  "furo",
  "pydata-sphinx-theme",
  "ipykernel",
  "toml"
]

[project.scripts]
pylegs = "pylegs.cli:entrypoint"

[project.urls]
Homepage = "https://nmcardoso.github.io/pylegs"
Documentation = "https://nmcardoso.github.io/pylegs"
Repository = "https://github.com/nmcardoso/pylegs"
Issues = "https://github.com/nmcardoso/pylegs/issues"
Changelog = "https://github.com/nmcardoso/pylegs/blob/main/CHANGELOG.md"