[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "gochocolatego"
version = "1.4-1"
authors = [{ name = "Chocolateisfr" }]
description = "A project manager CLI tool."
readme = "README.md"
license = { text = "MIT" }
dependencies = ["rich"]
requires-python = ">=3.7"

classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]

[project.scripts]
chocolate = "chocolate.__main__:main"
