[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "nexus_finance"
version = "1.2.3"
description = "Simulation for UserBase growth and financial forecast"
readme = "README.md"
authors = [
    { name = "Henrik Lorenzen", email = "h.lorenzen@nxs.solutions" }
]
dependencies = [
    "Flask",
    "flask_cors",
    "deap",
]
requires-python = ">=3.6"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: OS Independent",
]
urls = { "Homepage" = "https://github.com/anorien90/NexusFinance.git" }

[tool.setuptools]
include-package-data = true

[tool.setuptools.package-data]
"backend" = ["static/**/*"]  # This includes everything inside 'static'

